export const companySectors = [
  "Agroalimentaire",
  "Automobile",
  "Banque, Finance & Assurance",
  "BTP & Construction",
  "Commerce, Vente & Distribution",
  "Conseil & Services aux entreprises",
  "Éducation & Formation",
  "Énergie & Environnement",
  "Industrie & Ingénierie",
  "IT, Logiciels & Services Informatiques",
  "Juridique",
  "Luxe, Mode & Cosmétiques",
  "Marketing, Publicité & Médias",
  "Santé & Pharmaceutique",
  "Secteur Public & Administration",
  "Télécommunications",
  "Tourisme, Hôtellerie & Restauration",
  "Transport & Logistique",
  "Autre"
];
